---

- name: Stop and disable rabbitmq-server before database cleanup
  service: name=rabbitmq-server state=stopped enabled=no

- name: Delete rabbitmq-server database and config before creating image
  file: path="{{ item }}" state=absent
  with_items:
      - "{{ rabbitmq.dbdir }}/mnesia"
      - "{{ rabbitmq.dbdir }}/.erlang.cookie"
      - "{{ rabbitmq.cfgdir }}/rabbitmq-env.conf"

- name: Delete a temporary haproxy erigonesd SSL certificate
  file: path="{{ esdc_mgmt.erigonesd.ssl_file }}" state=absent

- name: Revert hostname back to localhost.localdomain
  hostname: name=localhost.localdomain
