- name: Check builder host
  hosts: builder
  tasks:
    - include: tasks/build/check.yml
      when: skip_check is not defined or not skip_check

- name: Create virtual machine
  hosts: buildnode
  vars_files:
    - vars/build/vm/access-zone.yml
  pre_tasks:
    - include: tasks/build/cleanup.yml
    - include: tasks/build/prepare-base-image.yml
  roles:
    - smartos-vm
  tasks:
    - include: tasks/build/zone/register-host.yml
        hostname=access-zone

- name: Install and configure appliance
  hosts: access-zone
  gather_facts: true
  vars_files:
    - vars/build/os/access-zone.yml
  roles:
    - esdc-common
    - zabbix-agent
    - access-zone
    - vm-image

- name: Create and save image
  hosts: buildnode
  vars_files:
    - vars/build/vm/access-zone.yml
  vars:
    image_tags: {internal: true, resize: true, deploy: false}
  tasks:
    - include: tasks/build/zone/create-image.yml
