- name: Check builder host
  hosts: builder
  tasks:
    - include: tasks/build/check.yml
      when: skip_check is not defined or not skip_check

- name: Create virtual machine
  hosts: buildnode
  vars_files:
    - vars/build/vm/contrib-centos-6.yml
  pre_tasks:
    - include: tasks/build/cleanup.yml
    - include: tasks/build/prepare-base-image.yml
  roles:
    - smartos-vm
  tasks:
    - include: tasks/build/centos/register-host.yml
        hostname=contrib-centos-6

- name: Install and configure appliance
  hosts: contrib-centos-6
  gather_facts: true
  vars_files:
    - vars/build/os/contrib-centos-6.yml
  roles:
    - iptables
    - cloud-init
    - mdata-client
    - qemu-guest-agent
    - vm-image

- name: Create and save image
  hosts: buildnode
  vars_files:
    - vars/build/vm/contrib-centos-6.yml
  tasks:
    - include: tasks/build/centos/create-image.yml
