---
- name: Create firewall configuration
  copy: src="{{ item }}"
        dest="/etc/ipf/{{ item }}"
        owner=root
        group=root
        mode=0644
  with_items:
      - ipf.conf
      - ipnat.conf

- name: Enable firewall service
  service: name=ipfilter enabled=yes state=started

- name: Enable packet forwarding
  command: /usr/sbin/routeadm -e ipv4-forwarding

      ---
- name: Copy firewall/portmap initilization script
  copy: src=31-firewall.sh
      dest=/var/zoneinit/includes/31-firewall.sh
      owner=root
      group=root
      mode=0755
