---
- name: Include OS-specific variables
  include_vars: ../defaults/{{ ansible_distribution }}.yml

- name: Install Zabbix repository package (CentOS)
  yum: name=http://repo.zabbix.com/zabbix/3.0/rhel/7/x86_64/zabbix-release-3.0-1.el7.noarch.rpm state=present
  when: ansible_distribution == "CentOS"

- name: Install Zabbix agent (CentOS)
  yum: name={{ item }} state=latest
  with_items:
    - zabbix-agent
    - zabbix-sender
  when: ansible_distribution == "CentOS"

- name: Install Zabbix agent (SmartOS)
  pkgin: name=zabbix-agent state=present
  when: ansible_distribution == "SmartOS"

- name: Create Zabbix agent configuration file
  template: src=zabbix_agentd.conf.j2
            dest={{ zabbix_agent_config_dir }}/zabbix_agentd.conf
            owner=root
            group=root
            mode=0644
  notify: restart zabbix-agent

- name: Place zabbix zoneinit script (SmartOS)
  copy: src=21-zabbix.sh
        dest=/var/zoneinit/includes/21-zabbix.sh
        mode=0755
        owner=root
        group=root
  when: ansible_distribution == "SmartOS"

- name: Disable Zabbix agent service (SmartOS)
  service: name=zabbix-agent state=stopped enabled=no
  when: ansible_distribution == "SmartOS"

- name: Ensure Zabbix agent is running and enabled
  service: name=zabbix-agent state=started enabled=yes
  when: ansible_distribution == "CentOS"
